### ISSUE TITLE
Change repository folder structure to better suit the use of Git Submodules in UE4 projects run off Git

### ISSUE THREAD

**Issue by BenjaminDSmithy** [getnamo/CIMPlugin#1]
Hi there,
If you could change the location of files from

CIMPlugin / Plugins / CIMPlugin / 

to

CIMPlugin /

then your plugin repository will support the setup of a Git Submodule under the MyProject\Plugins folder of any UE4 project running off Git

a good example is the plugin folder structure of [Git Source Control Plugin](https://github.com/SRombauts/UE4GitPlugin)

a reference of our use of a Git Submodule in 1 of our projects using Atlassian SourceTree
![Reference](http://i.gyazo.com/0df5a5bd8d3c7bdbc7f2456797abe57c.png)

**Comment by getnamo** [comment]
Ill try this, but for some plugins where you want more than one build or extra files I'm not convinced its the best way. It loses the ability to drag and drop easily (most projects don't have a plugins folder and if they do its safe to drop it on top) and I think this is the main use case.
