### ISSUE TITLE
problem with build 4.11.0

### ISSUE THREAD

**Issue by specters** [getnamo/CIMPlugin#2]
it doesn't work with build 4.11.0
error said "Plugin 'CIMPlugin' failed to load because module 'CIMPlugin' does not apear to be compatible with the current version of engine.my need to be recompiled."

I recompiled the engine with the plugin included but it failed

any help please....

**Comment by getnamo** [comment]
This plugin is largely archived, but you can add empty c++ code to your project and it will recompile the plugin for 4.11. 

From another plugin readme: Plugin recompiles require code, if you are using a blueprint only project, add an empty class and compile your project module. You simply do File->Add Code to Project and it can be anything so I usually just pick None->Create Class and then it will ask you to open visual studio where you just hit compile (Build solution).

**Comment by specters** [comment]
thx alot
but now i face this error

if (key != EKeysCIM::Unknown)
        FSlateApplication::Get().OnControllerButtonPressed(key, 0, 0);

Error   C2664   'bool FSlateApplication::OnControllerButtonPressed(FGamepadKeyNames::Type,int32,bool)': cannot convert argument 1 from 'FKey' to 'FGamepadKeyNames::Type'   MyProject_02    F:\Game DEV\UE4\MyProject_02\Plugins\CIMPlugin\Source\CIMPlugin\Private\FCIMPlugin.cpp  176

Error   C4390   ';': empty controlled statement found; is this the intent?  MyProject_02    F:\Game DEV\UE4\MyProject_02\Plugins\CIMPlugin\Source\CIMPlugin\Private\FCIMPlugin.cpp  175

**Comment by getnamo** [comment]
Although I still consider this plugin archived, the compile fixes were easy so see here: https://github.com/getnamo/CIMPlugin/commit/6253f6ea7a43d337a4d047b19e52be26124c4909 for the required code fixes.

The master branch now contains the plugin pre-compiled for 4.11. Enjoy!

**Comment by specters** [comment]
thank you sooooooo much
