### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by sofmz** [getnamo/CIMPlugin#3]
Hi, thanks for such wonderful and useful plugin. I can't find a LICENSE file in this plugin. Could I request you to add a LICENSE file for this plugin just like your other plugins for Unreal? I'll be much appreciated.

**Comment by getnamo** [comment]
Done: https://github.com/getnamo/CIMPlugin/blob/master/LICENSE

Enjoy

**Comment by sofmz** [comment]
Thanks a lot!
